# Generated by Django 4.2.11 on 2024-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe", name="cooking_time", field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="recipe", name="preparation_time", field=models.DurationField(),
        ),
    ]
