# Generated by Django 4.2.11 on 2024-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="preparation_time",
        ),
    ]
