# Generated by Django 4.2.11 on 2024-04-10 14:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_recipe_cooking_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="recipes/",
            ),
        ),
    ]
