# Generated by Django 4.2.11 on 2024-04-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_preparation_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="cooking_time",
        ),
        migrations.AddField(
            model_name="recipe",
            name="prep_time",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
