# Generated by Django 4.2.11 on 2024-04-13 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0007_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booked_recipe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
