# Generated by Django 4.2.11 on 2024-04-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_bookmark_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="recipe",
        ),
        migrations.AlterField(
            model_name="comment",
            name="title",
            field=models.CharField(default="Wonderful Recipe", max_length=200),
        ),
    ]
